name: docs
on:
  push: { branches: [main, develop] }
  pull_request: { branches: [main] }

permissions: { contents: read }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - run: python -m pip install --upgrade pip
      - run: pip install mkdocs mkdocs-material jinja2
      - name: Generate agent docs
        run: python scripts/gen_agent_docs.py
      - name: Enforce 150-word limit
        run: |
          python - <<'PY'
          import re, glob, sys, pathlib
          def wc(t):
              t = re.sub(r"```.*?```", "", t, flags=re.S)
              return len(re.findall(r"\b\w[\w-]*\b", t))
          bad=[]
          for p in glob.glob("docs/agents/*.md"):
              n = wc(pathlib.Path(p).read_text(encoding="utf-8"))
              if n>150: bad.append((p,n))
          if bad:
              [print(f"{p}: {n} words > 150") for p,n in bad]
              sys.exit(1)
          PY
      - name: Build site
        run: mkdocs build --strict